In [1]:
print("Hello World!")
print(4*5)

Hello World!
20

This is a text cell. Anything that you write here will not be considered code. 

print("Hello World!")

print(4*5)

You can add some 

1.   **formatting**
2.   and *other* elements

by using Markdown format, or using the buttons on the top of the cell.

You can see the preview of the contents on the right side panel.

# Organizing your notebook

If you use text headings 

Like these lines with the "#" symbol, you can generate a table of contents to navigate your notebook more easily.

## This is a Level 2 heading

You can have up to Level 6 heading, with 6 "#" symbols.

In [2]:
print("You can also run multiple code cells")

You can also run multiple code cells

In [3]:
print("From the menu 'Runtime'")

From the menu 'Runtime'

# Load Files From Drive

In [4]:
## To Load our CSV file into a dataframe
## First we need to provide access to our file

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Test loading CSV file

In [5]:
import pandas as pd

In [6]:
## Load csv file into a dataframe 

data_path = "/content/drive/MyDrive/FAI2223_Notebooks/data/test00.csv"
df = pd.read_csv(data_path)

## Check file loaded
df.head()

   id   color  age animal
0   1     red    5    cat
1   2     red   12    dog
2   3    blue    4  horse
3   4  yellow    7   fish

In [7]:
# Done.